global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ticketing-api"
    metrics_path: "/actuator/prometheus"
    basic_auth:
      username: "admin"
      password: "admin"
    static_configs:
      - targets: ["host.docker.internal:8080"]